name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install server dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests (optional)
      run: |
        cd backend
        npm test  # skip if you don't have tests

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build React app
      run: |
        cd frontend
        npm run build
